import { siteConfig } from '../config/site';

const pages = {
  about: {
    eyebrow:'About us', title:'Simple tools, useful answers.',
    body:<><p>CalcSyne is a lightweight calculator hub built to make everyday calculations easier to understand. The site combines focused tools with plain-language explanations, formulas, examples, and common questions.</p><h2>What we build</h2><p>Our calculators cover practical categories such as math, finance, education, health screening, dates, money, and unit conversions. The goal is not to replace professional advice or official institutional systems, but to give visitors a fast starting point for common calculations.</p><h2>Our approach</h2><p>We prioritize clear navigation, responsive design, transparent formulas, and useful content around each tool. Calculator inputs are processed locally in your browser, and no account or sign-up is required.</p><h2>Accuracy</h2><p>We aim to implement standard formulas carefully, but real-world organizations may use different assumptions, fees, rounding, policies, or eligibility rules. Important decisions should always be verified with the relevant professional or institution.</p></>
  },
  contact: {
    eyebrow:'Contact', title:'Get in touch.',
    body:<><p>Questions, corrections, partnership inquiries, or calculator suggestions are welcome.</p><div className="contact-card"><span>Email</span><strong>{siteConfig.supportEmail}</strong><a className="primary-button" href={`mailto:${siteConfig.supportEmail}`}>Send an email</a></div><h2>Report a calculator issue</h2><p>If you find an unexpected result, include the calculator name, the values you entered, the result you expected, and the result you received. That information makes it easier to reproduce and review the issue.</p><p className="calc-note"> <code>src/config/site.js</code> with an address on your real domain.</p></>
  },
  privacy: {
    eyebrow:'Legal', title:'Privacy Policy',
    body:<><p><strong>Last updated: September 1, 2026.</strong></p><p>This privacy policy explains how CalcSyne handles information when you use the website. CalcSyne is a frontend-based calculator website and does not require users to create an account..</p><h2>Calculator inputs</h2><p>Values entered into the included calculators are processed in your browser by the website code. The starter project does not intentionally transmit those calculator values to a custom server.</p><h2>Advertising and analytics</h2><p>If advertising or analytics services are enabled after launch, those third-party services may use cookies, device information, IP addresses, or similar technologies according to their own policies and applicable law. Update this policy to accurately describe every service you actually enable.</p><h2>Google AdSense</h2><p>If the site later uses Google AdSense, Google and its partners may use cookies or similar technologies to serve, measure, and personalize advertising where permitted. The site owner should configure the required consent tools and disclosures for the regions where the site operates.</p><h2>External links</h2><p>CalcSyne may link to third-party websites. We are not responsible for the privacy practices or content of external websites.</p><h2>Contact</h2><p>For privacy questions, contact {siteConfig.supportEmail}. Replace this placeholder address before publishing.</p></>
  },
  terms: {
    eyebrow:'Legal', title:'Terms of Use',
    body:<><p><strong>Last updated: September 1, 2026.</strong></p><p>By using CalcSyne, you agree to use the website and its calculators for lawful, informational purposes. If you do not agree with these terms, do not use the site.</p><h2>Informational results</h2><p>Calculator outputs are estimates based on the values you enter and the formulas implemented on the page. They are not professional financial, medical, legal, tax, academic, or investment advice.</p><h2>No warranty</h2><p>The website is provided on an “as is” and “as available” basis. While reasonable efforts may be made to maintain accurate tools, no guarantee is made that every result will be error-free, complete, or suitable for a particular purpose.</p><h2>Acceptable use</h2><p>Do not misuse the website, attempt to interfere with its operation, distribute malicious code, or use automated access in a way that harms availability for other visitors.</p><h2>Changes</h2><p>These terms may be updated as the website, features, advertising providers, or legal requirements change.</p></>
  },
  disclaimer: {
    eyebrow:'Legal', title:'Disclaimer',
    body:<><p>CalcSyne provides general-purpose calculators and educational explanations. Results are estimates and may not match calculations used by banks, schools, healthcare professionals, government agencies, tax authorities, employers, or other institutions.</p><h2>Financial calculators</h2><p>Loan and investment tools do not include every possible fee, tax, insurance cost, market condition, lender rule, or investment risk. They are not offers of credit or investment advice.</p><h2>Health calculators</h2><p>Health-related calculators such as BMI are screening tools only. They cannot diagnose a condition or account for every individual factor. Consult a qualified healthcare professional for personal medical advice.</p><h2>Education calculators</h2><p>Schools and universities may use different grading scales, weighting systems, rounding rules, dropped scores, or credit policies. Check your institution’s official rules.</p><h2>Use at your own discretion</h2><p>You are responsible for verifying important results before relying on them for decisions with financial, health, academic, tax, or legal consequences.</p></>
  }
};

export default function StaticPage({ type }) {
  const page=pages[type];
  return <section className="section page-top"><div className="container legal-layout"><article className="content-card legal-card"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1>{page.body}</article><aside><div className="sidebar-card"><h2>Need a calculator?</h2><p>Browse the complete tool library.</p><a className="secondary-button" href="/calculators/">View calculators</a></div></aside></div></section>;
}
